server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: loan-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/bookhub_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:my_db}
    password: ${SPRING_DATASOURCE_PASSWORD:book}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:myverysecretkeythatneedstobesecureandlongenoughforjwtverification123456}